version: "3.7"

services:
  legal_register_be_server:
    image: "legal_register_be_server"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  legal_register_reminder_job:
    image: "legal_register_reminder_job"
    build:
      context: .
      dockerfile: ./Dockerfile.reminder
    env_file: ./.env
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"